def test_cell5():

  local p1 = CELL1
  local p3 = CELL3
  local p7 = CELL7
  local p9 = CELL9

  # Promedio XYZ de las cuatro esquinas
  local x5 = (p1[0] + p3[0] + p7[0] + p9[0]) / 4.0
  local y5 = (p1[1] + p3[1] + p7[1] + p9[1]) / 4.0
  local z5 = (p1[2] + p3[2] + p7[2] + p9[2]) / 4.0

  # Orientación idéntica a CELL1
  local p5 = p[x5,y5,z5,p1[3],p1[4],p1[5]]

  textmsg("CELL5 CALCULADA", p5)

  # PRIMERA PRUEBA: dejar comentado
  # movel(p5, a=0.05, v=0.02)

end

test_cell5()